QA4Everyone3/group_vitalii

- test/pageobjects/Profile.page.js
https://trello.com/c/7KKuuGof/11-create-file-profilepage-in-pageobject
> profile page

- package.json
A new command "win_clean" should work correctly for Windows
> Upgrade command 'win_clean' from package.json

- test/pageobjects/Login.page.js
- test/specs/example.e2e.js
There are some minor changes in example of tests
> Login.page.js was updated

- test/pageobjects/Menu.page.js
https://trello.com/c/nopVgXTr/24-create-manu-page
> Created Menu Page

- test/pageobjects/Profile.page.js
https://trello.com/c/7KKuuGof/11-create-file-profilepage-in-pageobject
> Updated Profile Page

- test/data/login.data.js
- test/helpers/commonMethods/methods.js
- test/specs/login.spec.js
Added method clearInput
Added wrong credentials
Added test for the method clearInput
> Added method clearInput

- test/specs/people.spec.js
https://trello.com/c/OKUH0kEN/35-create-peoplespec-with-at-least-two-tcs
People.spec was created. Please, review and approve.
> Created People.spec

- test/pageobjects/ProblemsCreate.page.js
- Renamed class;
- Fixed selector for inputContent field.
> Updates for ProblemsCreatePage

- test/pageobjects/GlobalNavigation.page.js
- test/specs/companies.spec.js
- test/specs/people.spec.js
https://trello.com/c/4Bo26ZVE/45-refactor-menu-page-to-globalnavigationpage
> Refactor Menu Page to globalNavigationPage

- test/pageobjects/Problems.page.js
> add ProblemsPage

- test/helpers/commonMethods/methods.js
- test/pageobjects/Profile.page.js
- test/pageobjects/ProfileEdit.page.js
- test/specs/profileTest.spec.js
В этом пулреквесте случайно оказалось  три тикета, 
Знаю что надо разделять, но все еще эксперементирую. Пробовала как Женя сказал - по отдельности комитить и пушить из одной ветки, видимо не сработало.  Соррян. Виталик, Поступи как хочешь, можешь удалить, переделаю.
https://trello.com/c/sbEpT3ET/47-profile-edit-page-create-profile-page-change
https://trello.com/c/j51Yx9H1/48-add-methods-initials-into-folder-methods
https://trello.com/c/KIXhmb5B/36-create-profilespec-with-at-least-two-tcs
> Created Profile page and Changed Profile Page

- test/pageobjects/PublicationCreation.page.js
- test/pageobjects/Publications.page.js
> create PublicationCreation.page.js and add selectors

- test/pageobjects/OneCompany.page.js
There is no selectors for comment module
> Created OneCompany.page.js

- test/pageobjects/ProblemsCreate.page.js
- test/specs/Problems.spec.js
Added 2 tests to problems.spec.js and Added xpath btnBack to ProblemsCreate.page.js
> Added 2 tests to problems.spec.js and

- test/pageobjects/OneProblemProfile.page.js
- test/specs/Problems.spec.js
Added 1 test to problems.spec.js and OneProblemProfile.page.js
> Volha problem profile.page

- test/data/login.data.js
- test/helpers/apiMethods.js
- test/specs/api/userAuthApi.spec.js
API tests:
- added 4 different tests with comments for each of them;
- added 1 more API method that returns all the data of the response;
- added fake emails which can be used
All the tests passed (see screenshot)
> Vitalii add api tests

- test/pageobjects/Profile.page.js
- test/pageobjects/ProfileEdit.page.js
- test/specs/profileEditTest.spec.js
- test/specs/profileTest.spec.js
https://trello.com/c/sbEpT3ET/47-profile-edit-page-create-profile-page-update-profiletest-and-profileedit
> updated ProfileTest.spec.js, profileEditTest.spec.js, ProfileEdit.page.js; Profile.page.js

- test/pageobjects/SignUp.page.js
- test/specs/signUpTest.spec.js
https://trello.com/c/ZltQ3UCI/58-sign-up-page-sign-up-test
> Shouldn`t be able to sign up with existing email

- test/pageobjects/Publications.page.js
- test/specs/publications.spec.js
Added the test for the button "Like" : compare before and after click button.
> OK_like_btn

- test/specs/profileTest.spec.js
https://trello.com/c/kiGDHOUw/57-button-back-should-redirect-on-publication-page
> Button back should redirect on Publication Page

- test/specs/profileEditTest.spec.js
added few tests in profileEditTest.spec.js (Count Elements in dropdown, Count Selected Elements, compare them)
https://trello.com/c/V4E3z6yy/66-added-few-tests-in-profileedittestspecjs-count-elements-in-dropdown-count-selected-elements-compare-them
> added few tests in profileEditTest.spec.js

- test/pageobjects/SignUp.page.js
- test/specs/signUpTest.spec.js
https://trello.com/c/PY2hJqln/67-sign-up-user-is-not-able-to-sign-up-with-invalid-email
> added test with invalid emails

- test/helpers/uiMethods.js
- test/pageobjects/Companies.page.js
- test/specs/companies.spec.js
Tests were added to Companies.spec
https://trello.com/c/4NBE3jkZ/61-add-more-tests-in-companiesspec-look-inside-the-trello-card
https://trello.com/c/A8OlfHjL/60-add-more-tests-in-companiesspec-look-inside-the-trello-card
> Tests were added to Companies.spec

- test/pageobjects/Login.page.js
- test/pageobjects/SignUp.page.js
- test/specs/signUpTest.spec.js
https://trello.com/c/Bu6mnpoC/68-sign-up-should-redirect-the-user-from-signup-page-to-login-page-and-backwards
> Should redirect the user from SignUp Page to Login Page and backwards
